name: DevSecOps Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  security:
    name: Security Pipeline
    uses: frluty/pipeline-security/.github/workflows/reusable-security.yml@main
    permissions:
      contents:        read
      security-events: write
      packages:        write
      id-token:        write
      attestations:    write
      actions:         read
    with:
      language:              python
      image_name:            ${{ github.event.repository.name }}
      registry_type:         ghcr
      enable_signing:        true
      signing_mode:          keypair
      severity:              CRITICAL,HIGH
      fail_on_vulnerability: true
    secrets: inherit
